-- =====================================================
-- 说明：此脚本已废弃，无需执行
-- 
-- 原因：所有字段已合并至 init.sql
-- 
-- 原修改内容：
--   ALTER TABLE `wrong_question` ADD COLUMN `correct_answer` VARCHAR(10) DEFAULT NULL COMMENT '正确答案' AFTER `wrong_answer`;
--
-- 正式部署时只需执行 init.sql 即可创建完整表结构
-- =====================================================
